import '../models/place.dart';

/// Données de simulation (mode template, sans backend).
/// Reflète le seed Supabase : hôtels / restaurants / activités au Gabon.
class TemplateLodgingData {
  static final amenities = <AmenityOption>[
    const AmenityOption(key: 'wifi', label: 'Wi-Fi'),
    const AmenityOption(key: 'parking', label: 'Parking'),
    const AmenityOption(key: 'pool', label: 'Piscine'),
    const AmenityOption(key: 'breakfast', label: 'Petit-déjeuner'),
    const AmenityOption(key: 'air_conditioning', label: 'Climatisation'),
    const AmenityOption(key: 'restaurant', label: 'Restaurant'),
    const AmenityOption(key: 'bar', label: 'Bar'),
    const AmenityOption(key: 'beach_access', label: 'Accès plage'),
    const AmenityOption(key: 'airport_shuttle', label: 'Navette aéroport'),
    const AmenityOption(key: 'terrace', label: 'Terrasse'),
    const AmenityOption(key: 'family_friendly', label: 'Familial'),
    const AmenityOption(key: 'guide', label: 'Guide'),
  ];

  static final listings = <Place>[
    // ===================== HÔTELS =====================
    Place(
      id: 'template-h01',
      title: 'Hôtel boutique bord de mer',
      category: 'hotel',
      publicCode: 'GA-LBV-H01',
      description:
          'Chambres modernes face à l\'océan, idéales séjours affaires et week-ends à Libreville.',
      subtype: 'hotel',
      price: 82000,
      priceUnit: 'night',
      starRating: 4,
      guestRating: 8.6,
      reviewCount: 184,
      maxGuests: 2,
      address: 'Boulevard de la Mer',
      neighborhood: 'Batterie IV',
      city: 'Libreville',
      countryCode: 'GA',
      latitude: 0.4162,
      longitude: 9.4325,
      isFeatured: true,
      viewCount: 184,
      coverImageUrl: 'https://picsum.photos/seed/ga-h01/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-h01/800/600'],
      amenities: const ['Wi-Fi', 'Petit-déjeuner', 'Climatisation', 'Parking', 'Piscine'],
    ),
    Place(
      id: 'template-h02',
      title: 'Auberge centrale pour voyageurs',
      category: 'hotel',
      publicCode: 'GA-POG-H02',
      description:
          'Auberge simple et propre au centre de Port-Gentil, chambres privées et dortoirs.',
      subtype: 'hostel',
      price: 24000,
      priceUnit: 'night',
      starRating: 2,
      guestRating: 7.8,
      reviewCount: 96,
      maxGuests: 4,
      address: 'Avenue Savorgnan de Brazza',
      neighborhood: 'Centre-ville',
      city: 'Port-Gentil',
      countryCode: 'GA',
      latitude: -0.7193,
      longitude: 8.7815,
      viewCount: 96,
      coverImageUrl: 'https://picsum.photos/seed/ga-h02/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-h02/800/600'],
      amenities: const ['Wi-Fi', 'Restaurant', 'Climatisation'],
    ),
    Place(
      id: 'template-h03',
      title: 'Motel route nationale',
      category: 'hotel',
      publicCode: 'GA-FCV-H03',
      description:
          'Étape pratique à Franceville : parking sécurisé et arrivée tardive possible.',
      subtype: 'motel',
      price: 36000,
      priceUnit: 'night',
      starRating: 3,
      guestRating: 7.4,
      reviewCount: 71,
      maxGuests: 2,
      address: 'Route nationale',
      neighborhood: 'Potos',
      city: 'Franceville',
      countryCode: 'GA',
      latitude: -1.6333,
      longitude: 13.5833,
      viewCount: 71,
      coverImageUrl: 'https://picsum.photos/seed/ga-h03/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-h03/800/600'],
      amenities: const ['Parking', 'Climatisation', 'Restaurant'],
    ),
    Place(
      id: 'template-h04',
      title: 'Maison d\'hôtes familiale',
      category: 'hotel',
      publicCode: 'GA-OYM-H04',
      description:
          'Accueil familial chaleureux, idéal pour de courts séjours à Oyem.',
      subtype: 'guesthouse',
      price: 31000,
      priceUnit: 'night',
      guestRating: 8.1,
      reviewCount: 58,
      maxGuests: 3,
      neighborhood: 'Akoakam',
      city: 'Oyem',
      countryCode: 'GA',
      latitude: 1.5995,
      longitude: 11.5793,
      viewCount: 58,
      coverImageUrl: 'https://picsum.photos/seed/ga-h04/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-h04/800/600'],
      amenities: const ['Wi-Fi', 'Petit-déjeuner', 'Parking'],
    ),
    Place(
      id: 'template-h05',
      title: 'Resort lagune Pointe Denis',
      category: 'hotel',
      publicCode: 'GA-PDN-H05',
      description:
          'Bungalows pieds dans l\'eau face à la lagune, à 20 min en bateau de Libreville.',
      subtype: 'resort',
      price: 145000,
      priceUnit: 'night',
      starRating: 5,
      guestRating: 9.0,
      reviewCount: 132,
      maxGuests: 4,
      neighborhood: 'Pointe Denis',
      city: 'Pointe Denis',
      countryCode: 'GA',
      latitude: 0.3600,
      longitude: 9.3200,
      isFeatured: true,
      viewCount: 132,
      coverImageUrl: 'https://picsum.photos/seed/ga-h05/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-h05/800/600'],
      amenities: const ['Wi-Fi', 'Piscine', 'Restaurant', 'Bar', 'Accès plage', 'Navette aéroport'],
    ),

    // ===================== RESTAURANTS =====================
    Place(
      id: 'template-r01',
      title: 'Le Phare du Large',
      category: 'restaurant',
      publicCode: 'GA-LBV-R01',
      description:
          'Poissons et fruits de mer frais en bord de mer, spécialités gabonaises.',
      subtype: 'Poisson & fruits de mer',
      price: 15000,
      priceUnit: 'person',
      guestRating: 8.8,
      reviewCount: 240,
      maxGuests: 6,
      address: 'Bord de Mer',
      neighborhood: 'Quartier Louis',
      city: 'Libreville',
      countryCode: 'GA',
      latitude: 0.3920,
      longitude: 9.4530,
      isFeatured: true,
      viewCount: 240,
      coverImageUrl: 'https://picsum.photos/seed/ga-r01/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-r01/800/600'],
      amenities: const ['Wi-Fi', 'Climatisation', 'Bar', 'Terrasse'],
      details: const {'cuisine': 'Gabonaise', 'opening_hours': '12h - 23h'},
    ),
    Place(
      id: 'template-r02',
      title: 'Chez Tantine',
      category: 'restaurant',
      publicCode: 'GA-LBV-R02',
      description:
          'Cuisine africaine généreuse et conviviale, plats du jour à petit prix.',
      subtype: 'Cuisine africaine',
      price: 8000,
      priceUnit: 'person',
      guestRating: 8.2,
      reviewCount: 165,
      maxGuests: 4,
      address: 'Avenue de Cointet',
      neighborhood: 'Nombakélé',
      city: 'Libreville',
      countryCode: 'GA',
      latitude: 0.3950,
      longitude: 9.4570,
      viewCount: 165,
      coverImageUrl: 'https://picsum.photos/seed/ga-r02/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-r02/800/600'],
      amenities: const ['Familial', 'Terrasse'],
      details: const {'cuisine': 'Africaine', 'opening_hours': '11h - 22h'},
    ),
    Place(
      id: 'template-r03',
      title: 'La Terrasse',
      category: 'restaurant',
      publicCode: 'GA-POG-R03',
      description:
          'Grillades et cuisine internationale avec vue, ambiance détendue.',
      subtype: 'Grill & international',
      price: 18000,
      priceUnit: 'person',
      guestRating: 8.0,
      reviewCount: 98,
      maxGuests: 8,
      address: 'Boulevard du Bord de Mer',
      neighborhood: 'Centre',
      city: 'Port-Gentil',
      countryCode: 'GA',
      latitude: -0.7160,
      longitude: 8.7840,
      viewCount: 98,
      coverImageUrl: 'https://picsum.photos/seed/ga-r03/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-r03/800/600'],
      amenities: const ['Wi-Fi', 'Climatisation', 'Bar', 'Terrasse'],
      details: const {'cuisine': 'Internationale', 'opening_hours': '12h - 00h'},
    ),
    Place(
      id: 'template-r04',
      title: 'Saveurs d\'Oyem',
      category: 'restaurant',
      publicCode: 'GA-OYM-R04',
      description: 'Petite adresse locale, plats traditionnels du nord du Gabon.',
      subtype: 'Cuisine locale',
      price: 6000,
      priceUnit: 'person',
      guestRating: 7.6,
      reviewCount: 54,
      maxGuests: 4,
      address: 'Marché central',
      neighborhood: 'Centre',
      city: 'Oyem',
      countryCode: 'GA',
      latitude: 1.5990,
      longitude: 11.5800,
      viewCount: 54,
      coverImageUrl: 'https://picsum.photos/seed/ga-r04/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-r04/800/600'],
      amenities: const ['Familial'],
      details: const {'cuisine': 'Locale', 'opening_hours': '11h - 21h'},
    ),

    // ===================== ACTIVITÉS =====================
    Place(
      id: 'template-a01',
      title: 'Safari Parc national de la Lopé',
      category: 'activity',
      publicCode: 'GA-LPE-A01',
      description:
          'Observation de la faune (gorilles, éléphants de forêt) au cœur de la Lopé.',
      subtype: 'Safari',
      price: 45000,
      priceUnit: 'person',
      guestRating: 9.1,
      reviewCount: 210,
      maxGuests: 8,
      address: 'Parc de la Lopé',
      city: 'Lopé',
      countryCode: 'GA',
      latitude: -0.2000,
      longitude: 11.5900,
      isFeatured: true,
      viewCount: 210,
      coverImageUrl: 'https://picsum.photos/seed/ga-a01/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-a01/800/600'],
      amenities: const ['Guide', 'Familial'],
      details: const {'duration': 'Journée', 'difficulty': 'Modérée'},
    ),
    Place(
      id: 'template-a02',
      title: 'Journée plage à Pointe Denis',
      category: 'activity',
      publicCode: 'GA-PDN-A02',
      description:
          'Traversée en bateau et journée détente sur les plages de Pointe Denis.',
      subtype: 'Plage & détente',
      price: 20000,
      priceUnit: 'person',
      guestRating: 8.5,
      reviewCount: 175,
      maxGuests: 10,
      address: 'Embarcadère Michel Marine',
      city: 'Pointe Denis',
      countryCode: 'GA',
      latitude: 0.3600,
      longitude: 9.3200,
      viewCount: 175,
      coverImageUrl: 'https://picsum.photos/seed/ga-a02/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-a02/800/600'],
      amenities: const ['Accès plage', 'Familial'],
      details: const {'duration': 'Journée', 'difficulty': 'Facile'},
    ),
    Place(
      id: 'template-a03',
      title: 'Parc national de Loango',
      category: 'activity',
      publicCode: 'GA-LGO-A03',
      description:
          'Safari côtier unique : hippopotames surfeurs, baleines et forêt.',
      subtype: 'Safari',
      price: 90000,
      priceUnit: 'person',
      guestRating: 9.3,
      reviewCount: 142,
      maxGuests: 6,
      address: 'Loango',
      city: 'Loango',
      countryCode: 'GA',
      latitude: -2.1000,
      longitude: 9.6000,
      isFeatured: true,
      viewCount: 142,
      coverImageUrl: 'https://picsum.photos/seed/ga-a03/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-a03/800/600'],
      amenities: const ['Guide'],
      details: const {'duration': '2 jours', 'difficulty': 'Modérée'},
    ),
    Place(
      id: 'template-a04',
      title: 'Randonnée Chutes de Kongou',
      category: 'activity',
      publicCode: 'GA-IVD-A04',
      description:
          'Trek vers les impressionnantes chutes de Kongou dans le parc de l\'Ivindo.',
      subtype: 'Randonnée',
      price: 35000,
      priceUnit: 'person',
      guestRating: 8.7,
      reviewCount: 88,
      maxGuests: 8,
      address: 'Parc de l\'Ivindo',
      city: 'Ivindo',
      countryCode: 'GA',
      latitude: 0.3000,
      longitude: 12.6000,
      viewCount: 88,
      coverImageUrl: 'https://picsum.photos/seed/ga-a04/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-a04/800/600'],
      amenities: const ['Guide'],
      details: const {'duration': 'Journée', 'difficulty': 'Difficile'},
    ),
    Place(
      id: 'template-a05',
      title: 'Visite guidée de Libreville',
      category: 'activity',
      publicCode: 'GA-LBV-A05',
      description:
          'Découverte de la capitale : marché du Mont-Bouët, bord de mer et musées.',
      subtype: 'Visite de ville',
      price: 12000,
      priceUnit: 'person',
      guestRating: 7.9,
      reviewCount: 63,
      maxGuests: 12,
      neighborhood: 'Centre-ville',
      city: 'Libreville',
      countryCode: 'GA',
      latitude: 0.3920,
      longitude: 9.4540,
      viewCount: 63,
      coverImageUrl: 'https://picsum.photos/seed/ga-a05/800/600',
      imageUrls: const ['https://picsum.photos/seed/ga-a05/800/600'],
      amenities: const ['Guide', 'Familial'],
      details: const {'duration': 'Demi-journée', 'difficulty': 'Facile'},
    ),
  ];

  /// Établissements publiés par un annonceur en mode démo (en mémoire).
  static final List<Place> userPlaces = <Place>[];

  static List<Place> queryListings({
    UserLocation? userLocation,
    int offset = 0,
    int limit = PlaceServiceDefaults.pageSize,
    PlaceFilter filter = const PlaceFilter(),
    String searchQuery = '',
    bool requireCoordinates = false,
  }) {
    final filtered = [...userPlaces, ...listings].where((listing) {
      if (requireCoordinates && !listing.hasCoordinates) return false;
      return listing.matchesFilter(filter) && listing.matchesSearch(searchQuery);
    }).map((listing) => listing.copyWithDistance(userLocation)).toList();

    final start = offset.clamp(0, filtered.length);
    final end = (start + limit).clamp(start, filtered.length);
    return filtered.sublist(start, end);
  }
}

class PlaceServiceDefaults {
  static const pageSize = 20;
}
